#!/bin/bash

# Get the C file name from the environment variable
CFILE="$CFILE"

# Generate the output file name by replacing .c with .s
OUTFILE="${CFILE%.c}.s"

# Compile the C file to generate the assembly code
gcc -S -masm=intel "$CFILE" -o "$OUTFILE"

